{{ if .Values.auth.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-authservice"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/instance: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
    owner: KieniL
  annotations:
    email: test@test.at
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    container.apparmor.security.beta.kubernetes.io/{{ .Release.Name }}-authservice: runtime/default
spec:
  selector:
    matchLabels:
      app:  "{{ .Release.Name }}-authservice"
  template:
    metadata:
      labels:
        app:  "{{ .Release.Name }}-authservice"
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        container.apparmor.security.beta.kubernetes.io/{{ .Release.Name }}-authservice: runtime/default
        # AGENT INJECTOR SETTINGS
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-run-as-same-user: "true"
        # Application Properties SECRET
        vault.hashicorp.com/agent-inject-secret-application.properties: "k8s_secrets/family/authdb"
        vault.hashicorp.com/agent-inject-command-application.properties: "sh -c 'kill -HUP 1"
        vault.hashicorp.com/secret-volume-path-application.properties: /app/config
        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{`{{- with secret "k8s_secrets/family/authdb" -}}
          server.port=8080
          spring.application.name=familyauth
          management.health.probes.enabled=true
          spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/{{ .Data.db }}
          spring.datasource.username={{ .Data.username }}
          spring.datasource.password={{ .Data.password }}
          spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
          spring.jpa.hibernate.ddl-auto = update
          companyName=${COMPANY_NAME}
          logging.level.com.kienast.authservice=${AUTH_LOG_LEVEL}
          {{- end }}`}}
        # VAULT SETTINGS
        vault.hashicorp.com/role: 'auth-app'
    spec:
      serviceAccountName: {{ .Release.Name }}-authservice-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: "{{ .Release.Name }}-authservice"
              topologyKey: kubernetes.io/hostname
            weight: 100
      terminationGracePeriodSeconds: 40
      volumes:
      - name: tmp
        emptyDir:
          medium: Memory
          sizeLimit: 200Mi
      securityContext:
        runAsUser: 20000
        runAsGroup: 20000
        runAsNonRoot: true
      containers:
      - name:  "{{ .Release.Name }}-authservice"
        image: luke19/familyauthservice@{{ .Values.auth.image }}
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 20000
          runAsGroup: 20000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          privileged: false
          capabilities:
            drop:
              - all
        volumeMounts:
        - mountPath: /app/tmp
          name: tmp
        resources:
          limits:
            memory: "{{ .Values.auth.resources.memory_limit }}"
            cpu: "{{ .Values.auth.resources.cpu_limit }}"
          requests:
            memory: "{{ .Values.auth.resources.memory_request }}"
            cpu: "{{ .Values.auth.resources.cpu_request }}"
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-config"
              key: TZ
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-config"
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-config"
              key: DB_PORT
        - name: AUTH_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-config"
              key: AUTH_LOG_LEVEL
        - name: COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: "{{ .Release.Name }}-config"
              key: COMPANY_NAME
        ports:
        - containerPort: 8080 #Expose containerport to the pod
        livenessProbe: #Check that pod is ready
          httpGet:
            path: /actuator/health/liveness #path to check
            port: 8080
          initialDelaySeconds: 10 #start checking after 30 seconds
          periodSeconds: 10 #check every 30 seconds
          failureThreshold: 10
        readinessProbe: #Check that pod is healthy
          httpGet:
            path: /actuator/health/readiness #path to check
            port: 8080 #port to check
          initialDelaySeconds: 15 #start checking after 15 seconds
          periodSeconds: 10 #check every 3 seconds
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-authservice"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/instance: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
spec:
  type: ClusterIP
  ports:
   - port: 8080
     name: authservice
  selector:
   app: "{{ .Release.Name }}-authservice"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-authservice"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/instance: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-authservice"
  minReplicas: {{ .Values.auth.resources.hpa.min_replica }}
  maxReplicas: {{ .Values.auth.resources.hpa.max_replica }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.auth.resources.hpa.cpu_utilization }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}-authservice"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/instance: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-authservice"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-authservice"
{{ end }}