{
 "title": "Family Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Cert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\".*certservice\", namespace=\"family\"}[5m])",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=~\".*certservice\", namespace=\"family\"})",
     "legendFormat": "Container requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=~\".*certservice\", namespace=\"family\"})",
     "legendFormat": "Container limits"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=~\".*certservice\", namespace=\"family\"}[5m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "Memory Cert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\".*certservice\",namespace=\"family\"}",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{container=\".*certservice\",namespace=\"family\"})",
     "legendFormat": "Container Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\".*certservice\",namespace=\"family\"})",
     "legendFormat": "Cointainer limits"
    }
   ]
  },
  {
   "title": "Logs Cert",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container=~\".*certservice\", namespace=\"family\"}|json"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Frontend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\".*frontend\", namespace=\"family\"}[5m])",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=~\".*frontend\", namespace=\"family\"})",
     "legendFormat": "Container requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=~\"frontend\", namespace=\"family\"})",
     "legendFormat": "Container limits"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=~\".*frontend\", namespace=\"family\"}[5m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "Memory Frontend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\".*frontend\",namespace=\"family\"}",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{container=\".*frontend\",namespace=\"family\"})",
     "legendFormat": "Container Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\".*frontend\",namespace=\"family\"})",
     "legendFormat": "Cointainer limits"
    }
   ]
  },
  {
   "title": "Logs Frontend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{container=~\".*frontend\", namespace=\"family\"}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\".*apiservice\", namespace=\"family\"}[5m])",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=~\".*apiservice\", namespace=\"family\"})",
     "legendFormat": "Container requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=~\".*apiservice\", namespace=\"family\"})",
     "legendFormat": "Container limits"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=~\".*apiservice\", namespace=\"family\"}[5m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "Memory API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\".*apiservice\",namespace=\"family\"}",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{container=\".*apiservice\",namespace=\"family\"})",
     "legendFormat": "Container Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\".*apiservice\",namespace=\"family\"})",
     "legendFormat": "Cointainer limits"
    }
   ]
  },
  {
   "title": "Logs API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{container=~\".*apiservice\", namespace=\"family\"}"
    }
   ]
  },
  { "title": "Ansparen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Ansparen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\".*ansparservice\", namespace=\"family\"}[5m])",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=~\".*ansparservice\", namespace=\"family\"})",
     "legendFormat": "Container requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=~\".*ansparservice\", namespace=\"family\"})",
     "legendFormat": "Container limits"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=~\".*ansparservice\", namespace=\"family\"}[5m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "Memory Ansparen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\".*ansparservice\",namespace=\"family\"}",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{container=\".*ansparservice\",namespace=\"family\"})",
     "legendFormat": "Container Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\".*ansparservice\",namespace=\"family\"})",
     "legendFormat": "Cointainer limits"
    }
   ]
  },
  {
   "title": "Logs Ansparen",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{container=~\".*ansparservice\", namespace=\"family\"}"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "CPU Auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\".*authservice\", namespace=\"family\"}[5m])",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=~\".*authservice\", namespace=\"family\"})",
     "legendFormat": "Container requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=~\".*authservice\", namespace=\"family\"})",
     "legendFormat": "Container limits"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=~\".*authservice\", namespace=\"family\"}[5m])",
     "legendFormat": "throttling"
    }
   ]
  },
  {
   "title": "Memory Auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\".*authservice\",namespace=\"family\"}",
     "legendFormat": "Container usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{container=\".*authservice\",namespace=\"family\"})",
     "legendFormat": "Container Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\".*authservice\",namespace=\"family\"})",
     "legendFormat": "Cointainer limits"
    }
   ]
  },
  {
   "title": "Logs Auth",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "{container=~\".*authservice\", namespace= \"family\"}"
    }
   ]
  }
 ]
}