apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-rolebinding"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-rolebinding"
    app.kubernetes.io/instance: "{{ .Release.Name }}-rolebinding"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-rolebinding"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: "{{ .Release.Name }}-sa" # "name" is case sensitive
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: "{{ .Release.Name }}-role"