{{ if .Values.installer.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-installer-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-installer-serviceaccount"
    app.kubernetes.io/instance: "{{ .Release.Name }}-installer-serviceaccount"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-installer-serviceaccount"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
{{ end }}