apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-role"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-role"
    app.kubernetes.io/instance: "{{ .Release.Name }}-role"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-role"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployment"]
  verbs: ["get", "watch", "list"]