apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-ingress"
    app.kubernetes.io/instance: "{{ .Release.Name }}-ingress"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-ingress"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    enable-owasp-modsecurity-crs: "true"
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.limitrps }}"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.url }}
    secretName: {{ .Release.Name }}-tls-secret
  rules:
  - host: {{ .Values.ingress.url }}
    http:
      paths:
        {{ if .Values.testsuite.deploy }}
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: "{{ .Release.Name }}-testsuite"
              port:
                number: 8081
        {{ end }}
        - path: /frontend/
          pathType: ImplementationSpecific
          backend:
            service:
              name: "{{ .Release.Name }}-frontend"
              port:
                number: 8080
        - path: /api
          pathType: ImplementationSpecific
          backend:
            service:
              name: "{{ .Release.Name }}-apiservice"
              port:
                number: 8080
        

