apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-config"
    app.kubernetes.io/instance: "{{ .Release.Name }}-config"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-config"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
data:
  GUI_URL: "http://{{ .Release.Name }}-frontend:8080"
  TZ: "Europe/Berlin"
  PROJECT_NAME: "Family Testsuite"
  TAKE_SCREENSHOTS: FOR_EACH_ACTION