apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-rolebinding-podsecuritypolicy"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-rolebinding-podsecuritypolicy"
    app.kubernetes.io/instance: "{{ .Release.Name }}-rolebinding-podsecuritypolicy"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-rolebinding-podsecuritypolicy"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-role-podsecuritypolicy"
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize all service accounts in a namespace (recommended):
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts:{{ .Release.Namespace }}
