{{ if .Values.frontend.deploy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}-frontend"
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    app.kubernetes.io/name: "{{ .Release.Name }}-frontend"
    app.kubernetes.io/instance: "{{ .Release.Name }}-frontend"
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: "{{ .Release.Name }}-frontend"
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: helm
spec:
  podSelector: 
    matchLabels:
      app: "{{ .Release.Name }}-frontend"
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: monitoring
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress 
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: ingress
      ports:
      - protocol: TCP
        port: 8080
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name:  "{{ .Release.Name }}-connection-frontend-test"
      ports:
      - protocol: TCP
        port: 8080
    - from:
      - podSelector:
          matchLabels:
            app: "{{ .Release.Name }}-testsuite"
      ports:
      - protocol: TCP
        port: 8080
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          name: ingress 
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: ingress
{{ end }}