name: test helm release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  inital-setup:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.step1.outputs.date }}
    steps:
    - uses: actions/checkout@v2
    
    - id: step1
      name: Provided necessary things
      run: |
        DATE_TMP=$(date +%s)
        echo "DATE=$DATE_TMP" >> $GITHUB_ENV
        echo "::set-output name=date::$DATE_TMP"
        
        helm show values k8s/familychart/ > helmvalues.yaml
        helm template familyapp k8s/familychart/ --skip-tests --values k8s/familychart/values.yaml > helmtemplate.yaml
        
    - name: upload helmvalues
      uses: actions/upload-artifact@master
      with:
        name: helmvalues
        path: ./helmvalues.yaml
        if-no-files-found: error
        
    - name: upload helmtemplate
      uses: actions/upload-artifact@master
      with:
        name: helmtemplate
        path: ./helmtemplate.yaml
        if-no-files-found: error
      
  test_trivy_low_med_high:
    needs: inital-setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download helmvalues
      uses: actions/download-artifact@master
      with:
        name: helmvalues
    - name: Run trivy on low,medium high
      run: |
        cat helmvalues.yaml | docker run -i --rm mikefarah/yq e '.installer.image' - | xargs -n1 -I{} \
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $HOME/Library/Caches:/root/.cache/ \
        -v "$(pwd):/src" \
        aquasec/trivy \
        --exit-code 0 \
        --severity LOW,MEDIUM,HIGH \
        --format template --template "@contrib/junit.tpl" \
        -o src/junit-report-low-med-high.xml \
        --ignore-unfixed \
        'luke19/familycluster_installer@{}'
        
    - name: upload junit testresult
      uses: actions/upload-artifact@master
      with:
        name: junit-report-low-med-high
        path: ./junit-report-low-med-high
        if-no-files-found: error

  test_trivy_crit:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: download helmvalues
      uses: actions/download-artifact@master
      with:
        name: helmvalues
        
    - name: Run trivy on high
      run: |        
        cat helmvalues.yaml | docker run -i --rm mikefarah/yq e '.installer.image' - | xargs -n1 -I{} \
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $HOME/Library/Caches:/root/.cache/ \
        -v "$(pwd):/src" \
        aquasec/trivy \
        --exit-code 0 \
        --severity CRITICAL \
        --format template --template "@contrib/junit.tpl" \
        -o src/junit-report-crit.xml \
        --ignore-unfixed \
        'luke19/familycluster_installer@{}'
        
    - name: upload junit testresult
      uses: actions/upload-artifact@master
      with:
        name: junit-report-crit
        path: ./junit-report-crit.xml
        if-no-files-found: error

  test_checkov:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: download helmtemplate
      uses: actions/download-artifact@master
      with:
        name: helmtemplate
    - name: Run checkov
      run: |
        docker run --rm -t \
        -v"$(pwd):/helm" \
        bridgecrew/checkov \
        --quiet \
        --compact \
        --file /helm/helmtemplate.yaml \
        --output junitxml \
        --soft-fail > checkov.xml
    
    - name: upload checkov testresult
      uses: actions/upload-artifact@master
      with:
        name: checkov
        path: ./checkov.xml
        if-no-files-found: error
        
  final:
    needs: [inital-setup, test_trivy_low_med_high, test_trivy_crit, test_checkov]
    runs-on: ubuntu-latest
    
    steps:
    
    - name: download trivy low mid high result
      uses: actions/download-artifact@master
      with:
        name: junit-report-low-med-high
        
    - name: download trivy crit result
      uses: actions/download-artifact@master
      with:
        name: junit-report-crit
        
    - name: download checkov result
      uses: actions/download-artifact@master
      with:
        name: checkov
        
    - name: Move every result in test folder
      run: |
        mv junit-report-low-med-high.xml tests/junit-report-low-med-high_${{needs.inital-setup.outputs.date}}.xml
        mv junit-report-crit.xml tests/junit-report-crit_${{needs.inital-setup.outputs.date}}.xml
        mv checkov.xml  tests/checkov_${{needs.inital-setup.outputs.date}}.xml
        
    - name: clean before push
      run: |
        rm helmvalues.yaml
        rm helmtemplate.yaml
        
    - uses: EndBug/add-and-commit@v7
      with:
        message: Add test results
        committer_name: GitHub Actions
        committer_email: actions@github.com
