name: test helm release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  inital-setup:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.step1.outputs.date }}
    steps:
    - uses: actions/checkout@v2
    
    - id: step1
      name: Provided necessary things
      run: |
        DATE_TMP=$(date +%s)
        echo "DATE=$DATE_TMP" >> $GITHUB_ENV
        echo "::set-output name=date::$DATE_TMP"
      
  test_trivy_low_med_high:
    needs: inital-setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run trivy on low,medium high
      run: |
        helm show values k8s/familychart/ > helmvalues.yaml
         
        cat helmvalues.yaml | docker run -i --rm mikefarah/yq e '.installer.image' - | xargs -n1 -I{} \
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $HOME/Library/Caches:/root/.cache/ \
        -v "$(pwd):/src" \
        aquasec/trivy \
        --exit-code 0 \
        --severity LOW,MEDIUM,HIGH \
        --format template --template "@contrib/junit.tpl" \
        -o src/junit-report-low-med-high_${{needs.inital-setup.outputs.date}}.xml \
        --ignore-unfixed \
        'luke19/familycluster_installer@{}'

  test_trivy_crit:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run trivy on high
      run: |
        helm show values k8s/familychart/ > helmvalues.yaml
        
        cat helmvalues.yaml | docker run -i --rm mikefarah/yq e '.installer.image' - | xargs -n1 -I{} \
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $HOME/Library/Caches:/root/.cache/ \
        -v "$(pwd):/src" \
        aquasec/trivy \
        --exit-code 0 \
        --severity CRITICAL \
        --format template --template "@contrib/junit.tpl" \
        -o src/junit-report-crit_${{needs.inital-setup.outputs.date}}.xml \
        --ignore-unfixed \
        'luke19/familycluster_installer@{}'

  test_checkov:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run checkov
      run: |
        helm template familyapp k8s/familychart/ --skip-tests --values k8s/familychart/values.yaml > helmtemplate.yaml
        docker run --rm -t \
        -v"$(pwd):/helm" \
        bridgecrew/checkov \
        --quiet \
        --compact \
        -f /helm/helmtemplate.yaml \
        -o junitxml
        
  final:
    needs: [test_trivy_low_med_high, test_trivy_crit, test_checkov]
    runs-on: ubuntu-latest
    
    steps:
    - name: Move every result in test folder
      run: |
        mkdir -p tests
        mv junit-report-low-med-high_${{ env.DATE }}.xml tests/junit-report-low-med-high_${{ env.DATE }}.xml
        mv junit-report-crit_${{ env.DATE }}.xml tests/junit-report-crit_${{ env.DATE }}.xml
        
    - name: clean before push
      run: |
        rm helmvalues.yaml
        rm helmtemplate.yaml
        
    - uses: EndBug/add-and-commit@v7
      with:
        message: Add test results
        committer_name: GitHub Actions
        committer_email: actions@github.com
