name: test helm release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'tests/**'

jobs:
  inital-setup:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.step1.outputs.date }}
    steps:
    - uses: actions/checkout@v2
    
    - id: step1
      name: Provided necessary things
      run: |
        DATE_TMP=$(date +%s)
        echo "DATE=$DATE_TMP" >> $GITHUB_ENV
        echo "::set-output name=date::$DATE_TMP"
        
        helm show values k8s/familychart/ > helmvalues.yaml
        helm template familyapp k8s/familychart/ --skip-tests --values k8s/familychart/values.yaml > helmtemplate.yaml
        
    - name: upload helmvalues
      uses: actions/upload-artifact@master
      with:
        name: helmvalues
        path: ./helmvalues.yaml
        if-no-files-found: error
        
    - name: upload helmtemplate
      uses: actions/upload-artifact@master
      with:
        name: helmtemplate
        path: ./helmtemplate.yaml
        if-no-files-found: error


  test_dockerfile_lint:
    needs: inital-setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run dockerfile_lint
      run: |
        docker run --rm -v $PWD:/root/ \
        projectatomic/dockerfile-lint \
        dockerfile_lint \
        -u -f postman/Dockerfile \
        > dockerfile_lint.xml
        
    - name: upload junit testresult
      uses: actions/upload-artifact@master
      with:
        name: dockerfile_lint
        path: ./dockerfile_lint.xml
        if-no-files-found: error


  test_hadolint:
    needs: inital-setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run hadolint
      run: |
        docker run --rm -i \
        hadolint/hadolint hadolint \
        -f checkstyle \
        -t error \
        - < postman/Dockerfile \
        > hadolint.xml
        
    - name: upload junit testresult
      uses: actions/upload-artifact@master
      with:
        name: hadolint
        path: ./hadolint.xml
        if-no-files-found: error
  
  test_docker_conftest:
    needs: inital-setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run docker conftest
      run: |
        docker run --rm -i \
        -v $PWD:/totest \
        openpolicyagent/conftest test \
        --output junit \
        -p /totest/policy \
        /totest/postman/Dockerfile \
        > docker_conftest.xml | exit 0
        
    - name: upload junit testresult
      uses: actions/upload-artifact@master
      with:
        name: docker_conftest
        path: ./docker_conftest.xml
        if-no-files-found: error

  test_trivy_low_med_high:
    needs: inital-setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: download helmvalues
      uses: actions/download-artifact@master
      with:
        name: helmvalues

    - name: Run trivy on low,medium high
      run: |
        cat helmvalues.yaml | docker run -i --rm mikefarah/yq e '.postman.image' - | xargs -n1 -I{} \
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $HOME/Library/Caches:/root/.cache/ \
        -v "$(pwd):/src" \
        aquasec/trivy \
        --exit-code 0 \
        --severity LOW,MEDIUM,HIGH \
        --format template --template "@contrib/junit.tpl" \
        -o src/junit-report-low-med-high.xml \
        --ignore-unfixed \
        'luke19/familypostman@{}'
        
    - name: upload junit testresult
      uses: actions/upload-artifact@master
      with:
        name: junit-report-low-med-high
        path: ./junit-report-low-med-high.xml
        if-no-files-found: error

  test_trivy_crit:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: download helmvalues
      uses: actions/download-artifact@master
      with:
        name: helmvalues
        
    - name: Run trivy on high
      run: |        
        cat helmvalues.yaml | docker run -i --rm mikefarah/yq e '.postman.image' - | xargs -n1 -I{} \
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $HOME/Library/Caches:/root/.cache/ \
        -v "$(pwd):/src" \
        aquasec/trivy \
        --exit-code 0 \
        --severity CRITICAL \
        --format template --template "@contrib/junit.tpl" \
        -o src/junit-report-crit.xml \
        --ignore-unfixed \
        'luke19/familypostman@{}'
        
    - name: upload junit testresult
      uses: actions/upload-artifact@master
      with:
        name: junit-report-crit
        path: ./junit-report-crit.xml
        if-no-files-found: error

  test_checkov:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: download helmtemplate
      uses: actions/download-artifact@master
      with:
        name: helmtemplate
    - name: Run checkov
      run: |
        docker run --rm -t \
        -v "$(pwd):/helm" \
        bridgecrew/checkov \
        --quiet \
        --compact \
        --file /helm/helmtemplate.yaml \
        --output junitxml \
        --soft-fail > checkov.xml
    
    - name: upload checkov testresult
      uses: actions/upload-artifact@master
      with:
        name: checkov
        path: ./checkov.xml
        if-no-files-found: error

  test_datree:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: download helmtemplate
      uses: actions/download-artifact@master
      with:
        name: helmtemplate

    - name: Run datree
      run: |
        docker run --rm \
        -v "$(pwd):/helm" \
        -i datree/datree \
        test /helm/helmtemplate.yaml \
        --schema-version 1.21.0 \
        --output xml \
        > datree.xml | exit 0
    
    - name: upload datree testresult
      uses: actions/upload-artifact@master
      with:
        name: datree
        path: ./datree.xml
        if-no-files-found: error

  test_helm_conftest:
    needs: inital-setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: download helmtemplate
      uses: actions/download-artifact@master
      with:
        name: helmtemplate
    
    - name: Run docker conftest
      run: |
        docker run --rm -i \
        -v $PWD:/totest \
        openpolicyagent/conftest test \
        --output junit \
        -p /totest/policy \
        /totest/helmtemplate.yaml \
        > helm_conftest.xml | exit 0
        
    - name: upload junit testresult
      uses: actions/upload-artifact@master
      with:
        name: helm_conftest
        path: ./helm_conftest.xml
        if-no-files-found: error

  test_kubescape_nsa:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: download helmtemplate
      uses: actions/download-artifact@master
      with:
        name: helmtemplate

    - name: Run kubescape_nsa
      run: |
        docker run --rm \
        -v $(pwd):/helm \
        -i quay.io/armosec/kubescape \
        scan framework nsa \
        /helm/helmtemplate.yaml \
        --keep-local true \
        --format junit \
        --silent \
        > kubescape_nsa.xml
    
    - name: upload datree testresult
      uses: actions/upload-artifact@master
      with:
        name: kubescape_nsa
        path: ./kubescape_nsa.xml
        if-no-files-found: error

  test_kubescape_mitre:
    needs: inital-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: download helmtemplate
      uses: actions/download-artifact@master
      with:
        name: helmtemplate

    - name: Run kubescape_mitre
      run: |
        docker run --rm \
        -v $(pwd):/helm \
        -i quay.io/armosec/kubescape \
        scan framework mitre \
        /helm/helmtemplate.yaml \
        --keep-local true \
        --format junit \
        --silent \
        > kubescape_mitre.xml
    
    - name: upload datree testresult
      uses: actions/upload-artifact@master
      with:
        name: kubescape_mitre
        path: ./kubescape_mitre.xml
        if-no-files-found: error
        
  final:
    needs: [inital-setup, test_hadolint, test_dockerfile_lint, test_helm_conftest, test_docker_conftest, test_trivy_low_med_high, test_trivy_crit, test_checkov, test_datree, test_kubescape_nsa, test_kubescape_mitre]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: download kubescape_nsa result
      uses: actions/download-artifact@master
      with:
        name: kubescape_nsa

    - name: download kubescape_mitre result
      uses: actions/download-artifact@master
      with:
        name: kubescape_mitre

    - name: download hadolint result
      uses: actions/download-artifact@master
      with:
        name: hadolint

    - name: download dockerfile_lint result
      uses: actions/download-artifact@master
      with:
        name: dockerfile_lint

    - name: download docker_conftest result
      uses: actions/download-artifact@master
      with:
        name: docker_conftest

    - name: download trivy low mid high result
      uses: actions/download-artifact@master
      with:
        name: junit-report-low-med-high
        
    - name: download trivy crit result
      uses: actions/download-artifact@master
      with:
        name: junit-report-crit
        
    - name: download checkov result
      uses: actions/download-artifact@master
      with:
        name: checkov

    - name: download datree result
      uses: actions/download-artifact@master
      with:
        name: datree

    - name: download helm_conftest result
      uses: actions/download-artifact@master
      with:
        name: helm_conftest

        
    - name: Move every result in test folder
      run: |
        mv docker_conftest.xml tests/${{needs.inital-setup.outputs.date}}_docker_conftest.xml
        mv hadolint.xml tests/${{needs.inital-setup.outputs.date}}_hadolint.xml
        mv dockerfile_lint.xml tests/${{needs.inital-setup.outputs.date}}_dockerfile_lint.xml
        mv junit-report-low-med-high.xml tests/${{needs.inital-setup.outputs.date}}_junit-report-low-med-high.xml
        mv junit-report-crit.xml tests/${{needs.inital-setup.outputs.date}}_junit-report-crit.xml
        mv checkov.xml  tests/${{needs.inital-setup.outputs.date}}_checkov.xml
        mv datree.xml  tests/${{needs.inital-setup.outputs.date}}_datree.xml
        mv helm_conftest.xml tests/${{needs.inital-setup.outputs.date}}_helm_conftest.xml
        mv kubescape_nsa.xml tests/${{needs.inital-setup.outputs.date}}_kubescape_nsa.xml
        mv kubescape_mitre.xml tests/${{needs.inital-setup.outputs.date}}_kubescape_mitre.xml

    - name: clean before push
      run: |
        rm helmvalues.yaml || true
        rm helmtemplate.yaml || true

    - uses: EndBug/add-and-commit@v7
      with:
        message: Add test results
        committer_name: GitHub Actions
        committer_email: actions@github.com
